// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzLQ-qmvyvB31VkbEjZwvgDCpA7AbkJns',
    appId: '1:244505639274:web:b9d049a4c2c53dfc12cd13',
    messagingSenderId: '244505639274',
    projectId: 'primex-e522d',
    authDomain: 'primex-e522d.firebaseapp.com',
    storageBucket: 'primex-e522d.firebasestorage.app',
    measurementId: 'G-VK2TM2GVGK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuWMMswTXaEJhyqUeU2TSOJ1Z8GRZN8bc',
    appId: '1:244505639274:ios:03753349e0a26d6412cd13',
    messagingSenderId: '244505639274',
    projectId: 'primex-e522d',
    storageBucket: 'primex-e522d.firebasestorage.app',
    iosClientId:
        '244505639274-012f9cgl4rb1ihqudhqvvoecos89fnr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.primexMarketplace',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCMTwFHLD_we56VJICtE_rRMYNM0qTb6Q',
    appId: '1:244505639274:ios:4b71aee131b6c05212cd13',
    messagingSenderId: '244505639274',
    projectId: 'primex-e522d',
    storageBucket: 'primex-e522d.firebasestorage.app',
    iosClientId:
        '244505639274-b2i4milatip4ihahlh156gj54oarlodo.apps.googleusercontent.com',
    iosBundleId: 'com.primex.marketplace',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCskLqMc5hFZTJTQMXdBMFj8rHs-wDNnFQ',
    appId: '1:244505639274:android:5e94770ece83af7112cd13',
    messagingSenderId: '244505639274',
    projectId: 'primex-e522d',
    storageBucket: 'primex-e522d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3xztBTScCa6fdJNZNVgaOfu8p0mXDQvI',
    appId: '1:244505639274:web:c24b24399d784b6612cd13',
    messagingSenderId: '244505639274',
    projectId: 'primex-e522d',
    authDomain: 'primex-e522d.firebaseapp.com',
    storageBucket: 'primex-e522d.firebasestorage.app',
    measurementId: 'G-WW62F918H7',
  );
}
